# Generated by Django 5.0.4 on 2024-04-18 21:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0007_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=255)),
                ('current_amount', models.PositiveIntegerField()),
                ('target_amount', models.PositiveIntegerField()),
                ('acheived', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('transactions', models.ManyToManyField(to='transaction.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
