# Generated by Django 5.0.4 on 2024-04-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_goal_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='current_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
