# Generated by Django 5.0.4 on 2024-04-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0005_alter_goal_current_amount'),
        ('transaction', '0007_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='transaction.transaction'),
        ),
    ]
