# Generated by Django 5.0.4 on 2024-04-18 04:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('saving', 'saving'), ('expense', 'expense'), ('income', 'income')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
