# Generated by Django 5.0.4 on 2024-04-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('savings', 'savings'), ('expense', 'expense'), ('income', 'income')], max_length=255),
        ),
    ]
